### ISSUE TITLE
comment on simulation results

### ISSUE THREAD

**Issue by stephens999** [gaow/pfar#9]
in https://gaow.github.io/dr-tree/doc/documentation/20170328_More_Data_on_Nodes.html
the results for the Y-shape tree are concerning in that the weight (pi) on node 1 is 0 when it should
be non-trivial.

What is the likelihood for the fitted parameter values (pi,F)?
what is the likelihood for the true parameter values?
is it a problem with local optimum?

**Comment by gaow** [comment]
I will revisit this after I get some real data results. But for this case we cannot have loglik for "true parameter" values because it is under Brownian motion simulation, not paired factor model. I can do the same thing for paired factor model and compare the true loglik with the fitted loglik and i'll update as a separate notebook. The reason I did Brownian motion is because this data projects very well on PC space while under the PF model the visualization on edges is bad. But we'll check the weight matrix and loglik for that case.

**Comment by gaow** [comment]
> is it a problem with local optimum?

To answer this i'll run both simulations with different seeds and see.

**Comment by kkdey** [comment]
Is this analysis done on the usual grid set up of q=0.001 to q=1, that might explain that most of the points are assigned to the edge at small values of q rather than getting assigned to the node exactly. I think if the variation of points assigned to each node is made smaller or the grid made sparser , we may not see 0 weights on nodes

**Comment by gaow** [comment]
@kkdey There is not any officially documented, that are done correctly with 1/Q, for usual grid setup. This is to be uploaded. But the reason we dropped 1/Q was because we did not like what we saw with 1/Q on that usual setup. 

This ticket is on the package repo. I'll move it over to the project repo and follow it up from there.
